topic:
  hub-event-topic: telemetry.hubs.v1
  snapshots-topic: telemetry.snapshots.v1

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: HubEventConsumer
      group-id: hubEvent.group.id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
      enable-auto-commit: false
      snapshot-client-id: SnapshotEventConsumer
      snapshot-group-id: snapshotEvent.group.id
      snapshot-value-deserializer: ru.yandex.practicum.kafka.deserializer.SnapshotDeserializer
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scenario
    username: postgres
    password: "12345"

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext